name: Compile LaTeX to PDF
on:
  push:
    paths:
      - '**.tex'
      - '.github/workflows/*'


jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex

      - name: ls -Al
        run: |
          ls -Al out/

