name: Compile LaTeX to PDF
on:
  push:
    paths:
      - '**.tex'
      - '.github/workflows/*'


jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@latest
        with:
          root_file: main.tex

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: out/main.pdf
