name: Compile and Deploy CV

on:
  push:
    branches: ["main"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: create index.html
        run: |
          mkdir dist
          echo "<!DOCTYPE html>
                <html>
                  <head>
                    <title>CV | Kristofer Fannar</title>
                  </head>
                  <body>
                    <h1>CV</h1>
                    <object data='../out/main.pdf' type="application/pdf" width="100%" height="500px">
                      <p>Unable to display PDF file. <a href='../out/main.pdf'>Download</a> instead.</p>
                    </object>
                  </body>
                </html>" > dist/index.html


      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: out/main.pdf

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
